<?php
/*
Ajax Form Generated by Brendon Irwin's Form Generator
Query Form: "Testcase" Object 


ajaxTableTestcase.php 

*/

		include "include.php";

		$type = $_GET["type"];

		$draw = $_GET["draw"];

		$start = $_GET["start"];

		$length =  (int)($_GET["length"]);

		$orderBy = (int)$_GET["order"][0]["column"];

		$orderDir = $_GET["order"][0]["dir"];

		$orderDir = ($orderDir == "asc" ? "ASC" : "DESC");

		$search = isset($_GET['search']['value']) ? $_GET['search']['value'] : '';

		if( $search != ""){

			$search = "%".$search."%";

		}

		if( $start < 0 || !is_int($start) ){

			$start = 0;

		}

		$conn = getConnection();

		$query = "SELECT COUNT(`id`) as `cnt` FROM `testcase`";

		$result = $conn->prepare($query);

		$result->execute();

		$result = $result->fetchAll(PDO::FETCH_ASSOC);

		$recordsTotal = $result[0]['cnt'];

		if( $orderBy != "" && is_int($orderBy) ){

			switch($orderBy){

				case 0:

					$orderBy = "testcase.`id`";

				break;

				case 1:

					$orderBy = "`tid`";

				break;

				case 2:

					$orderBy = "`description`";

				break;

				case 3:

					$orderBy = "`applicable`";

				break;

				case 4:

					$orderBy = "`requirements`";

				break;

				case 5:

					$orderBy = "`comments`";

				break;

				default:

					$orderBy = "`id`";

				break;

			}

		}else{

			$orderBy = "`id`";

		}

		$query = "SELECT `id`,

			`tid`,`description`,`applicable`,`requirements`,`comments`

		FROM

			`testcase`

		WHERE

			".( $search != "" ? " (`tid` ".($search != "" ? " LIKE :SEARCH" : "").") OR (`description` ".($search != "" ? " LIKE :SEARCH" : "").") OR (`applicable` ".($search != "" ? " LIKE :SEARCH" : "").") OR (`requirements` ".($search != "" ? " LIKE :SEARCH" : "").") OR (`comments` ".($search != "" ? " LIKE :SEARCH" : "").")" : " 1 ") ."

		ORDER BY

			".$orderBy." ".$orderDir."

		LIMIT :START,:LENGTH";

		$result = $conn->prepare($query);

		$result->bindParam(':LENGTH', $length, PDO::PARAM_INT);

		$result->bindParam(':START', $start, PDO::PARAM_INT);

		if( $search != ""){

			$result->bindParam(':SEARCH', $search, PDO::PARAM_STR);

		}

		$result->execute();	

		$results = $result->fetchAll(PDO::FETCH_ASSOC);

		foreach( $results as $row){

		$id = $row['id'];

		$data[] =  array(

			$row["id"], $row["tid"], $row["description"], $row["applicable"], $row["requirements"], $row["comments"], "<!--[ <a href='modifyTestcase.php?testcaseID=$id'>Modify</a><a href='deleteTestcase.php?testcaseID=$id'>Delete</a>]--> <a href='takeTestcase.php?testcaseID=$id'>TAKE TEST</a>"

		);

		}

		if( sizeof($results) == 0 ){ $data = array(); }

		$recordsFiltered =  sizeof( $data ) ;

		ob_clean();

		echo json_encode( array( "draw" => (int)($draw), "recordsTotal" => $recordsTotal, "recordsFiltered" => $recordsFiltered, "data" => $data, "error" => "") ); 

		exit;
?>