<?php
/*
Ajax Form Generated by Brendon Irwin's Form Generator
Query Form: "Testresult" Object 


ajaxTableTestresult.php 

*/

		include "include.php";

		$type = $_GET["type"];

		$draw = $_GET["draw"];

		$start = $_GET["start"];

		$length =  (int)($_GET["length"]);

		$orderBy = (int)$_GET["order"][0]["column"];

		$orderDir = $_GET["order"][0]["dir"];

		$orderDir = ($orderDir == "asc" ? "ASC" : "DESC");

		$search = isset($_GET['search']['value']) ? $_GET['search']['value'] : '';

		if( $search != ""){

			$search = "%".$search."%";

		}

		if( $start < 0 || !is_int($start) ){

			$start = 0;

		}

		$conn = getConnection();

		$query = "SELECT COUNT(`id`) as `cnt` FROM `testresult`";

		$result = $conn->prepare($query);

		$result->execute();

		$result = $result->fetchAll(PDO::FETCH_ASSOC);

		$recordsTotal = $result[0]['cnt'];

		if( $orderBy != "" && is_int($orderBy) ){

			switch($orderBy){

				case 0:

					$orderBy = "testresult.`id`";

				break;

				case 1:

					$orderBy = "`testID`";

				break;

				case 2:

					$orderBy = "`testName`";

				break;

				case 3:

					$orderBy = "`testNum`";

				break;

				case 4:

					$orderBy = "`pass`";

				break;

				case 5:

					$orderBy = "`fail`";

				break;

				case 6:

					$orderBy = "`taker`";

				break;

				default:

					$orderBy = "`id`";

				break;

			}

		}else{

			$orderBy = "`id`";

		}

		$query = "SELECT `id`,

			`testID`,`testName`,`testNum`,`pass`,`fail`,`taker`

		FROM

			`testresult`

		WHERE

			".( $search != "" ? " (`testID` ".($search != "" ? " LIKE :SEARCH" : "").") OR (`taker` ".($search != "" ? " LIKE :SEARCH" : "").") OR (`html` ".($search != "" ? " LIKE :SEARCH" : "").")" : " 1 ") ."

		ORDER BY

			".$orderBy." ".$orderDir."

		LIMIT :START,:LENGTH";

		$result = $conn->prepare($query);

		$result->bindParam(':LENGTH', $length, PDO::PARAM_INT);

		$result->bindParam(':START', $start, PDO::PARAM_INT);

		if( $search != ""){

			$result->bindParam(':SEARCH', $search, PDO::PARAM_STR);

		}

		$result->execute();	

		$results = $result->fetchAll(PDO::FETCH_ASSOC);

		foreach( $results as $row){

		$id = $row['id'];

		$data[] =  array(

			$row["id"], $row["testID"], $row["testName"], $row["testNum"], $row["pass"], $row["fail"], $row["taker"], "<a href='modifyTestresult.php?testresultID=$id'>View</a>   <a href='deleteTestresult.php?testresultID=$id'>Delete</a>"

		);

		}

		if( sizeof($results) == 0 ){ $data = array(); }

		$recordsFiltered =  sizeof( $data ) ;

		ob_clean();

		echo json_encode( array( "draw" => (int)($draw), "recordsTotal" => $recordsTotal, "recordsFiltered" => $recordsFiltered, "data" => $data, "error" => "") ); 

		exit;
?>