<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Create Form: "Testresult" Object -->


<!-- createTestresult.php -->



<?php
	include "include.php";

	include "Testresult.php";

	$conn = getConnection(); //set to DB Conn
	$testresult = new Testresult($conn);
	$showForm = 1;
	if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {
		$testresult->getFromPost();
		if( $testresult->save() > 0 && $testresult->getErrorCount() == 0){
			echo "<p>Testresult saved successfully!</p>";
			echo "<p><a href='createTestresult.php'>Add anotherTestresult</a> or <a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
			$showForm = 0;
		}else{
			echo "<p>Testresult contained (".$testresult->getErrorCount().") error(s).</p>";
			echo "<p>Errors: ".$testresult->getErrors()."</p>";
			echo "<p><a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
		}
	}
	if( $showForm == 1){
?>
<form name="createTestresult" id="createTestresult" method="POST" action="createTestresult.php" enctype="multipart/form-data">
	<div class="formRow">
		<div class="rowLabel">
			<label for="testID">Test ID:*</label>
		</div>
		<div class="rowField">
			<input type="text" name="testID" id="testID" value="<?php echo (isset($testresult) ?  $testresult->getTestID() : ''); ?>"  title="Test ID is a required field. " required="required"/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="testName">Test Name:</label>
		</div>
		<div class="rowField">
			<input type="text" name="testName" id="testName" value="<?php echo (isset($testresult) ?  $testresult->getTestName() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="testNum">test Number:</label>
		</div>
		<div class="rowField">
			<input type="text" name="testNum" id="testNum" value="<?php echo (isset($testresult) ?  $testresult->getTestNum() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="pass">Pass Count:</label>
		</div>
		<div class="rowField">
			<input type="text" name="pass" id="pass" value="<?php echo (isset($testresult) ?  $testresult->getPass() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="fail">Fail Count:</label>
		</div>
		<div class="rowField">
			<input type="text" name="fail" id="fail" value="<?php echo (isset($testresult) ?  $testresult->getFail() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="taker">Test Taker:</label>
		</div>
		<div class="rowField">
			<input type="text" name="taker" id="taker" value="<?php echo (isset($testresult) ?  $testresult->getTaker() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="html">HTML:</label>
		</div>
		<div class="rowField">
			<textarea  name="html" id="html"  title="" ><?php echo (isset($testresult) ?  $testresult->getHtml() : ''); ?></textarea>
		</div>
	</div>
	<div class="formRow rowCenter">
		<input class="button" type="submit" value="Save" /> <a href="TestresultAdmin.php">Cancel</a>
	</div>
</form>
<?php } ?>