<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Create Form: "Testcase" Object -->


<!-- createTestcase.php -->



<?php
	include "include.php";

	include "Testcase.php";

	$conn = getConnection(); //set to DB Conn
	$testcase = new Testcase($conn);
	$showForm = 1;
	if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {
		$testcase->getFromPost();
		
		//echo '<pre>'.print_r($_POST,true).'</pre>';
		if( isset($_POST) && isset( $_POST['step'] ) ){
			$StepIDs = [];
			include "Steps.php";
			if( is_array($_POST['step']) ){
				//many options
				for($x=0; $x < sizeof( $_POST['step'] ); $x++){
					//$conn = getConnection();
					// $conn->setAttribute(PDO::ATTR_TIMEOUT, 300); 
					$steps = new Steps($conn);
					$steps->setID(  		$_POST['stepsID'][$x]		);
					$steps->setStep(		$_POST['step'][$x]			);
					$steps->setRegression(	$_POST['regression'][$x]	);
					$steps->setResult(		$_POST['result'][$x]		);
					$steps->setPass(		$_POST['pass'][$x]			);
					
					if( $steps->save() > 0 ){
						$StepIDs[] = $steps->getId();
					}
					
				}	
				
				//echo '<pre>'.print_r($StepIDs,true).'</pre>';
				
			}else{
				if( sizeof($_POST['step']) == 1 ){
					$steps = new Steps($conn);
					$steps->setID(  		$_POST['stepsID']	);
					$steps->setStep(		$_POST['step']		);
					$steps->setRegression(	$_POST['regression']);
					$steps->setResult(		$_POST['result']	);
					$steps->setPass(		$_POST['pass']		);
					
					if( $steps->save() > 0 ){
						$StepIDs[] = $steps->getId();
					}
				}
			}
			
			
			$testcase->setSteps( implode(',',$StepIDs) ); 
			
		} 
		
		//exit;
		
		if( $testcase->save() > 0 && $testcase->getErrorCount() == 0){
			echo "<p>Testcase saved successfully!</p>";
			
			
			
			
			
			echo "<p><a href='createTestcase.php'>Add anotherTestcase</a> or <a href='TestcaseAdmin.php'>Go back to Testcase management area</a></p>";
			$showForm = 0;
		}else{
			echo "<p>Testcase contained (".$testcase->getErrorCount().") error(s).</p>";
			echo "<p>Errors: ".$testcase->getErrors()."</p>";
			echo "<p><a href='TestcaseAdmin.php'>Go back to Testcase management area</a></p>";
		}
	}
	if( $showForm == 1){
?>
<script   src="https://code.jquery.com/jquery-2.2.3.min.js"   integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="   crossorigin="anonymous"></script>



<style>
td{ vertical-align: top; }
</style>

<form name="createTestcase" id="createTestcase" method="POST" action="createTestcase.php" enctype="multipart/form-data" novalidate>
	<div class="formRow">
		<div class="rowLabel">
			<label for="tid">Test Case ID:*</label>
		</div>
		<div class="rowField">
			<input type="text" name="tid" id="tid" value="CSWT<?php
				$nid = $conn->query("SELECT Auto_increment FROM information_schema.tables WHERE table_name='testcase' AND table_schema='testcase';");
				if( $nid->execute() ){
					$nid = $nid->fetch();
					echo  str_pad($nid[0],3, "0",STR_PAD_LEFT);
				}
			?>"  title="Test Case ID is a required field. " required="required"/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="description">Description:</label>
		</div>
		<div class="rowField">
			<textarea class="wysiwyg"  name="description" id="description"  title="" ><?php echo (isset($testcase) ?  $testcase->getDescription() : ''); ?></textarea>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="applicable">Author:</label>
		</div>
		<div class="rowField">
			<input type="text" name="applicable" id="applicable" value="<?php echo (isset($testcase) ?  $testcase->getApplicable() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="requirements">Requirements:</label>
		</div>
		<div class="rowField">
			<input type="text" name="requirements" id="requirements" value="<?php echo (isset($testcase) ?  $testcase->getRequirements() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="steps">Steps:</label>
		</div>
		<div class="rowField">
			<fieldset>
		
				<input type="hidden"  name="steps" id="steps" value="<?php echo (isset($testcase) ?  $testcase->getSteps() : ''); ?>" />
				
			<?php
				$cases = (isset($testcase) ?  $testcase->getSteps() : ''); 
				
				if( $cases != ''){
					//load the cases
				}
			?>
				
				<div id="Steps">
				
				</div>
				
				<button id="addStep">Add Step</button>
			</fieldset>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="comments">Comments:</label>
		</div>
		<div class="rowField">
			<textarea class="wysiwyg"  name="comments" id="comments"  title="" ><?php echo (isset($testcase) ?  $testcase->getComments() : ''); ?></textarea>
		</div>
	</div>
	<div class="formRow rowCenter">
	<br />
	<br />
		<input class="button" type="submit" value="Save" /> <a href="TestcaseAdmin.php">Cancel</a>
	</div>
</form>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
	var step;


	$(function(){
		
		step = $('#Steps .step').length + 1;
		
		
		$('#addStep').click(function(event){
			event.preventDefault();
			$.get("addStep.php?n=0&step=" + step, function( my_var ) {
				$('#Steps').append(my_var);
				step = step + 1;
				
			}, 'html').always(function() {
				$('#Steps .step:last-child textarea').each(function(){
					var d = new Date();
					var n = d.getMilliseconds();
					$(this).attr('id', 'ta_' + n );
					tinymce.init({ selector: 'textarea#ta_' + n, plugins: [
        "image paste"
       // "searchreplace visualblocks",
      //  "insertdatetime media contextmenu "
    ],
   // convert_urls: false,
    paste_data_images: true });
					
				});
				
				
			});
		
		});
	});
	
	tinymce.init({ selector:'textarea', plugins: [
        "image paste"
    ],
    paste_data_images: true});
	
	
</script>
<!--
<script>
var IMAGE_MIME_REGEX = /^image\/(p?jpeg|gif|png)$/i;

var loadImage = function (file) {
    var reader = new FileReader();
    reader.onload = function(e){
        var img = document.createElement('img');
        img.src = e.target.result;
        
        var range = window.getSelection().getRangeAt(0);
        range.deleteContents();
        range.insertNode(img);
    };
    reader.readAsDataURL(file);
};

document.onpaste = function(e){
    var items = e.clipboardData.items;
	console.log("here");
    for (var i = 0; i < items.length; i++) {
        if (IMAGE_MIME_REGEX.test(items[i].type)) {
            loadImage(items[i].getAsFile());
            return;
        }
    }
    
    // Normal paste handling here
}
</script>
-->
<?php } ?>