<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Delete Form: "Steps" Object -->


<!-- deleteSteps.php -->


<?php
		include "include.php";

		$conn = getConnection(); //create DB Connection 

		include "Steps.php";

		$steps = new Steps( $conn );



		if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){

			$stepsID = $_POST["stepsID"];

			$steps = $steps->load( $stepsID );

			if( $steps->delete() ){

				echo "<p>Steps deleted Successfully</p>";

				echo "<p><a href='createSteps.php'>Create Steps</a> or <a href='StepsAdmin.php'>Go back to Steps management area</a></p>";
			}else{

				echo "<p>Error! Could not delete Steps</p>";

				echo "<p><a href='StepsAdmin.php'>Go back to Steps management area</a></p>";
			}

		}else{

			$stepsID = $_REQUEST["stepsID"];

			$steps = $steps->load( $stepsID );

			if( $steps->getID() > 0 ){

			?>

				<form method="post" action="deleteSteps.php">

					<p>Are you sure you wish to delete Steps with ID of: <?php  echo $stepsID; ?></p>

					<input type="hidden" name="stepsID" value ="<?php echo $steps->getId(); ?>"/>

					<input type="submit" value="Yes" /> <a href="StepsAdmin.php">Cancel</a>

				</form>

			<?php

			}else{

				echo "<p>Error! Could not load Steps</p>";

			}

		}
?>
