<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Delete Form: "Testresult" Object -->


<!-- deleteTestresult.php -->


<?php
		include "include.php";

		$conn = getConnection(); //create DB Connection 

		include "Testresult.php";

		$testresult = new Testresult( $conn );



		if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){

			$testresultID = $_POST["testresultID"];

			$testresult = $testresult->load( $testresultID );

			if( $testresult->delete() ){

				echo "<p>Testresult deleted Successfully</p>";

				echo "<p><a href='createTestresult.php'>Create Testresult</a> or <a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
			}else{

				echo "<p>Error! Could not delete Testresult</p>";

				echo "<p><a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
			}

		}else{

			$testresultID = $_REQUEST["testresultID"];

			$testresult = $testresult->load( $testresultID );

			if( $testresult->getID() > 0 ){

			?>

				<form method="post" action="deleteTestresult.php">

					<p>Are you sure you wish to delete Testresult with ID of: <?php  echo $testresultID; ?></p>

					<input type="hidden" name="testresultID" value ="<?php echo $testresult->getId(); ?>"/>

					<input type="submit" value="Yes" /> <a href="TestresultAdmin.php">Cancel</a>

				</form>

			<?php

			}else{

				echo "<p>Error! Could not load Testresult</p>";

			}

		}
?>
