<?php
/* Form Generated by Brendon Irwin's Form Generator
<!--Create Form: "Steps" Object -->


<!-- exportSteps.php -->

*/

	include "include.php";

	include "Steps.php";

	if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){

	$conn = getConnection();

		$select = "SELECT ";
		$select = $select.(( isset($_POST["step"]) && $_POST["step"] == 1 ) ? "`step`, " : "");
		$select = $select.(( isset($_POST["regression"]) && $_POST["regression"] == 1 ) ? "`regression`, " : "");
		$select = $select.(( isset($_POST["result"]) && $_POST["result"] == 1 ) ? "`result`, " : "");
		$select = $select.(( isset($_POST["pass"]) && $_POST["pass"] == 1 ) ? "`pass`, " : "");
		$select = substr($select, 0, -2);
		$select = $select." FROM `Steps`;";
		$query = $conn->prepare( $select );
		if( $query->execute() ){
			header("Content-type: text/csv");
			header("Content-Disposition: attachment; filename=export.csv");
			header("Pragma: no-cache");
			header("Expires: 0");
			$results = $query->fetchAll(PDO::FETCH_ASSOC);	
		echo (( isset($_POST["step"]) && $_POST["step"] == 1 ) ? "Step, " : "");
		echo (( isset($_POST["regression"]) && $_POST["regression"] == 1 ) ? "Full Regression, " : "");
		echo (( isset($_POST["result"]) && $_POST["result"] == 1 ) ? "Task and Expected Result, " : "");
		echo (( isset($_POST["pass"]) && $_POST["pass"] == 1 ) ? "Pass / Fail, " : "");
			echo PHP_EOL;
			foreach($results as $r){
				echo implode(",", str_replace( ",", "", $r) ).PHP_EOL;
			}
			echo PHP_EOL;
			exit;
		}else{
			$error = "";
		}
	}
?>
<div class="toggles">
	<script>
		var opts = '<option  value="step">Step</option><option  value="regression">Full Regression</option><option  value="result">Task and Expected Result</option><option  value="pass">Pass / Fail</option>';
		var controls = '<div class="remove">X</div>';
		$(function(){
			function bind(){
				$(".remove").click(function(){ $(this).parent().remove(); }); 
			}
			$('#addClause').click(function(){
						$('#clauses').append('<div class="clause">WHERE <select name="where[]">' + opts + '</select> <select name="operator[]"><option value="LIKE">LIKE</option><option value="EQUAL">EQUALS</option></select> <input name="filterString[]" /><div class="controls">' + controls + '</div></div>');
				bind();
			});
			$('input[name="addWhere"]').change(function(){ if($(this).val() == "Yes"){ $("whereClaue").show(); }else{ $("whereClause").hide(); } }); 
		});
	</script>
	<form class="toggles" method="POST" action="exportSteps.php">
		<p>Check the following boxes to add them to the report:</p>
		<input type="checkbox" name="step" value="1" <?php echo ( isset($_POST["step"]) && $_POST["step"] == 1 ) ? "checked" : ""; ?>/>: Step<br />
		<input type="checkbox" name="regression" value="1" <?php echo ( isset($_POST["regression"]) && $_POST["regression"] == 1 ) ? "checked" : ""; ?>/>: Full Regression<br />
		<input type="checkbox" name="result" value="1" <?php echo ( isset($_POST["result"]) && $_POST["result"] == 1 ) ? "checked" : ""; ?>/>: Task and Expected Result<br />
		<input type="checkbox" name="pass" value="1" <?php echo ( isset($_POST["pass"]) && $_POST["pass"] == 1 ) ? "checked" : ""; ?>/>: Pass / Fail<br />
		<p>Configure where clause? <input type="radio" name="addWhere" value="Yes" />Yes <input name="where" value="No" /> No </p>
		<fieldset id="whereClause" style="display: none;">
			<legend>Filter Data - Where</legend>
			<div id="clauses"></div>
			<button id="addClause">Add Clause</button>
		</fieldset>
		<p><input type="submit" value="GENERATE CSV"/></p>
	</form>
</div>