<?php
/* Form Generated by Brendon Irwin's Form Generator
<!--Create Form: "Testcase" Object -->


<!-- exportTestcase.php -->

*/

	include "include.php";

	include "Testcase.php";

	if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){

	$conn = getConnection();

		$select = "SELECT ";
		$select = $select.(( isset($_POST["tid"]) && $_POST["tid"] == 1 ) ? "`tid`, " : "");
		$select = $select.(( isset($_POST["description"]) && $_POST["description"] == 1 ) ? "`description`, " : "");
		$select = $select.(( isset($_POST["applicable"]) && $_POST["applicable"] == 1 ) ? "`applicable`, " : "");
		$select = $select.(( isset($_POST["requirements"]) && $_POST["requirements"] == 1 ) ? "`requirements`, " : "");
		$select = $select.(( isset($_POST["steps"]) && $_POST["steps"] == 1 ) ? "`steps`, " : "");
		$select = $select.(( isset($_POST["comments"]) && $_POST["comments"] == 1 ) ? "`comments`, " : "");
		$select = substr($select, 0, -2);
		$select = $select." FROM `Testcase`;";
		$query = $conn->prepare( $select );
		if( $query->execute() ){
			header("Content-type: text/csv");
			header("Content-Disposition: attachment; filename=export.csv");
			header("Pragma: no-cache");
			header("Expires: 0");
			$results = $query->fetchAll(PDO::FETCH_ASSOC);	
		echo (( isset($_POST["tid"]) && $_POST["tid"] == 1 ) ? "Test Case ID, " : "");
		echo (( isset($_POST["description"]) && $_POST["description"] == 1 ) ? "Description, " : "");
		echo (( isset($_POST["applicable"]) && $_POST["applicable"] == 1 ) ? "Applicable For, " : "");
		echo (( isset($_POST["requirements"]) && $_POST["requirements"] == 1 ) ? "Requirements, " : "");
		echo (( isset($_POST["steps"]) && $_POST["steps"] == 1 ) ? "Steps, " : "");
		echo (( isset($_POST["comments"]) && $_POST["comments"] == 1 ) ? "Comments, " : "");
			echo PHP_EOL;
			foreach($results as $r){
				echo implode(",", str_replace( ",", "", $r) ).PHP_EOL;
			}
			echo PHP_EOL;
			exit;
		}else{
			$error = "";
		}
	}
?>
<div class="toggles">
	<script>
		var opts = '<option  value="tid">Test Case ID</option><option  value="description">Description</option><option  value="applicable">Applicable For</option><option  value="requirements">Requirements</option><option  value="steps">Steps</option><option  value="comments">Comments</option>';
		var controls = '<div class="remove">X</div>';
		$(function(){
			function bind(){
				$(".remove").click(function(){ $(this).parent().remove(); }); 
			}
			$('#addClause').click(function(){
						$('#clauses').append('<div class="clause">WHERE <select name="where[]">' + opts + '</select> <select name="operator[]"><option value="LIKE">LIKE</option><option value="EQUAL">EQUALS</option></select> <input name="filterString[]" /><div class="controls">' + controls + '</div></div>');
				bind();
			});
			$('input[name="addWhere"]').change(function(){ if($(this).val() == "Yes"){ $("whereClaue").show(); }else{ $("whereClause").hide(); } }); 
		});
	</script>
	<form class="toggles" method="POST" action="exportTestcase.php">
		<p>Check the following boxes to add them to the report:</p>
		<input type="checkbox" name="tid" value="1" <?php echo ( isset($_POST["tid"]) && $_POST["tid"] == 1 ) ? "checked" : ""; ?>/>: Test Case ID<br />
		<input type="checkbox" name="description" value="1" <?php echo ( isset($_POST["description"]) && $_POST["description"] == 1 ) ? "checked" : ""; ?>/>: Description<br />
		<input type="checkbox" name="applicable" value="1" <?php echo ( isset($_POST["applicable"]) && $_POST["applicable"] == 1 ) ? "checked" : ""; ?>/>: Applicable For<br />
		<input type="checkbox" name="requirements" value="1" <?php echo ( isset($_POST["requirements"]) && $_POST["requirements"] == 1 ) ? "checked" : ""; ?>/>: Requirements<br />
		<input type="checkbox" name="steps" value="1" <?php echo ( isset($_POST["steps"]) && $_POST["steps"] == 1 ) ? "checked" : ""; ?>/>: Steps<br />
		<input type="checkbox" name="comments" value="1" <?php echo ( isset($_POST["comments"]) && $_POST["comments"] == 1 ) ? "checked" : ""; ?>/>: Comments<br />
		<p>Configure where clause? <input type="radio" name="addWhere" value="Yes" />Yes <input name="where" value="No" /> No </p>
		<fieldset id="whereClause" style="display: none;">
			<legend>Filter Data - Where</legend>
			<div id="clauses"></div>
			<button id="addClause">Add Clause</button>
		</fieldset>
		<p><input type="submit" value="GENERATE CSV"/></p>
	</form>
</div>