<?php
/* Form Generated by Brendon Irwin's Form Generator
<!--Create Form: "Testresult" Object -->


<!-- exportTestresult.php -->

*/

	include "include.php";

	include "Testresult.php";

	if (strtoupper($_SERVER["REQUEST_METHOD"]) == "POST"){

	$conn = getConnection();

		$select = "SELECT ";
		$select = $select.(( isset($_POST["testID"]) && $_POST["testID"] == 1 ) ? "`testID`, " : "");
		$select = $select.(( isset($_POST["testName"]) && $_POST["testName"] == 1 ) ? "`testName`, " : "");
		$select = $select.(( isset($_POST["testNum"]) && $_POST["testNum"] == 1 ) ? "`testNum`, " : "");
		$select = $select.(( isset($_POST["pass"]) && $_POST["pass"] == 1 ) ? "`pass`, " : "");
		$select = $select.(( isset($_POST["fail"]) && $_POST["fail"] == 1 ) ? "`fail`, " : "");
		$select = $select.(( isset($_POST["taker"]) && $_POST["taker"] == 1 ) ? "`taker`, " : "");
		$select = $select.(( isset($_POST["html"]) && $_POST["html"] == 1 ) ? "`html`, " : "");
		$select = substr($select, 0, -2);
		$select = $select." FROM `Testresult`;";
		$query = $conn->prepare( $select );
		if( $query->execute() ){
			header("Content-type: text/csv");
			header("Content-Disposition: attachment; filename=export.csv");
			header("Pragma: no-cache");
			header("Expires: 0");
			$results = $query->fetchAll(PDO::FETCH_ASSOC);	
		echo (( isset($_POST["testID"]) && $_POST["testID"] == 1 ) ? "Test ID, " : "");
		echo (( isset($_POST["testName"]) && $_POST["testName"] == 1 ) ? "Test Name, " : "");
		echo (( isset($_POST["testNum"]) && $_POST["testNum"] == 1 ) ? "test Number, " : "");
		echo (( isset($_POST["pass"]) && $_POST["pass"] == 1 ) ? "Pass Count, " : "");
		echo (( isset($_POST["fail"]) && $_POST["fail"] == 1 ) ? "Fail Count, " : "");
		echo (( isset($_POST["taker"]) && $_POST["taker"] == 1 ) ? "Test Taker, " : "");
		echo (( isset($_POST["html"]) && $_POST["html"] == 1 ) ? "HTML, " : "");
			echo PHP_EOL;
			foreach($results as $r){
				echo implode(",", str_replace( ",", "", $r) ).PHP_EOL;
			}
			echo PHP_EOL;
			exit;
		}else{
			$error = "";
		}
	}
?>
<div class="toggles">
	<script>
		var opts = '<option  value="testID">Test ID</option><option  value="testName">Test Name</option><option  value="testNum">test Number</option><option  value="pass">Pass Count</option><option  value="fail">Fail Count</option><option  value="taker">Test Taker</option><option  value="html">HTML</option>';
		var controls = '<div class="remove">X</div>';
		$(function(){
			function bind(){
				$(".remove").click(function(){ $(this).parent().remove(); }); 
			}
			$('#addClause').click(function(){
						$('#clauses').append('<div class="clause">WHERE <select name="where[]">' + opts + '</select> <select name="operator[]"><option value="LIKE">LIKE</option><option value="EQUAL">EQUALS</option></select> <input name="filterString[]" /><div class="controls">' + controls + '</div></div>');
				bind();
			});
			$('input[name="addWhere"]').change(function(){ if($(this).val() == "Yes"){ $("whereClaue").show(); }else{ $("whereClause").hide(); } }); 
		});
	</script>
	<form class="toggles" method="POST" action="exportTestresult.php">
		<p>Check the following boxes to add them to the report:</p>
		<input type="checkbox" name="testID" value="1" <?php echo ( isset($_POST["testID"]) && $_POST["testID"] == 1 ) ? "checked" : ""; ?>/>: Test ID<br />
		<input type="checkbox" name="testName" value="1" <?php echo ( isset($_POST["testName"]) && $_POST["testName"] == 1 ) ? "checked" : ""; ?>/>: Test Name<br />
		<input type="checkbox" name="testNum" value="1" <?php echo ( isset($_POST["testNum"]) && $_POST["testNum"] == 1 ) ? "checked" : ""; ?>/>: test Number<br />
		<input type="checkbox" name="pass" value="1" <?php echo ( isset($_POST["pass"]) && $_POST["pass"] == 1 ) ? "checked" : ""; ?>/>: Pass Count<br />
		<input type="checkbox" name="fail" value="1" <?php echo ( isset($_POST["fail"]) && $_POST["fail"] == 1 ) ? "checked" : ""; ?>/>: Fail Count<br />
		<input type="checkbox" name="taker" value="1" <?php echo ( isset($_POST["taker"]) && $_POST["taker"] == 1 ) ? "checked" : ""; ?>/>: Test Taker<br />
		<input type="checkbox" name="html" value="1" <?php echo ( isset($_POST["html"]) && $_POST["html"] == 1 ) ? "checked" : ""; ?>/>: HTML<br />
		<p>Configure where clause? <input type="radio" name="addWhere" value="Yes" />Yes <input name="where" value="No" /> No </p>
		<fieldset id="whereClause" style="display: none;">
			<legend>Filter Data - Where</legend>
			<div id="clauses"></div>
			<button id="addClause">Add Clause</button>
		</fieldset>
		<p><input type="submit" value="GENERATE CSV"/></p>
	</form>
</div>