<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Update Form: "Testresult" Object -->


<!-- modifyTestresult.php -->



<?php
	include "include.php";

	include "Testresult.php";

	$conn = getConnection(); //set to DB Conn
	$testresult = new Testresult($conn);
	$showForm = 1;
	if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {
		$testresult->getFromPost();
		$testresult->setID( $_POST["testresultID"] );
		if( $testresult->save() > 0 && $testresult->getErrorCount() == 0){
			echo "<p>Testresult updated successfully!</p>";
			echo "<p><a href='createTestresult.php'>Create new Testresult</a> or <a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
			$showForm = 0;
		}else{
			echo "<p>Testresult contained (".$testresult->getErrorCount().") error(s).</p>";
			echo "<p>Errors: ".$testresult->getErrors()."</p>";
			echo "<p><a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
		}
	}else{
		$testresultID = $_REQUEST["testresultID"];

		$testresult = $testresult->load( $testresultID );

		if( $testresult->getID() > 0 ){
		}else{
			$showForm = 0;
			echo "<p>Could not load Testresult with ID of ".$testresultID."</p>";
		}
	}
	if( $showForm == 1){
?>
<form name="modifyTestresult" id="modifyTestresult" method="POST" action="modifyTestresult.php" enctype="multipart/form-data">
	<div class="formRow">
		<div class="rowLabel">
			<label for="testID">Test ID:*</label>
		</div>
		<div class="rowField">
			<input type="text" name="testID" id="testID" value="<?php echo (isset($testresult) ?  $testresult->getTestID() : ''); ?>"  title="Test ID is a required field. " required="required" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="testName">Test Name:</label>
		</div>
		<div class="rowField">
			<input type="text" name="testName" id="testName" value="<?php echo (isset($testresult) ?  $testresult->getTestName() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="testNum">test Number:</label>
		</div>
		<div class="rowField">
			<input type="text" name="testNum" id="testNum" value="<?php echo (isset($testresult) ?  $testresult->getTestNum() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="pass">Pass Count:</label>
		</div>
		<div class="rowField">
			<input type="text" name="pass" id="pass" value="<?php echo (isset($testresult) ?  $testresult->getPass() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="fail">Fail Count:</label>
		</div>
		<div class="rowField">
			<input type="text" name="fail" id="fail" value="<?php echo (isset($testresult) ?  $testresult->getFail() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="taker">Test Taker:</label>
		</div>
		<div class="rowField">
			<input type="text" name="taker" id="taker" value="<?php echo (isset($testresult) ?  $testresult->getTaker() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowField">
			<?php echo (isset($testresult) ?  $testresult->getHtml() : ''); ?>
		</div>
	</div>
	<div class="formRow rowCenter">
	<!--
		<input type="hidden" name="testresultID" value="<?php echo $testresult->getID(); ?>" /> <input class="button" type="submit" value="Update" /> 
	-->	
	
	<a href="TestresultAdmin.php">Go Back</a>
	
	</div>
</form>
<?php } ?>