<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Update Form: "Testresult" Object -->


<!-- modifyTestresult.php -->



<?php
	include "include.php";

	include "Testresult.php";

	$conn = getConnection(); //set to DB Conn
	$testresult = new Testresult($conn);
	$showForm = 1;
	if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {
		$testresult->getFromPost();
		$testresult->setID( $_POST["testresultID"] );
		if( $testresult->save() > 0 && $testresult->getErrorCount() == 0){
			echo "<p>Testresult updated successfully!</p>";
			echo "<p><a href='createTestresult.php'>Create new Testresult</a> or <a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
			$showForm = 0;
		}else{
			echo "<p>Testresult contained (".$testresult->getErrorCount().") error(s).</p>";
			echo "<p>Errors: ".$testresult->getErrors()."</p>";
			echo "<p><a href='TestresultAdmin.php'>Go back to Testresult management area</a></p>";
		}
	}else{
		$testresultID = $_REQUEST["testresultID"];

		$testresult = $testresult->load( $testresultID );

		if( $testresult->getID() > 0 ){
			
		}else{
			$showForm = 0;
			echo "<p>Could not load Testresult with ID of ".$testresultID."</p>";
		}
	}
	if( $showForm == 1){
?>

<style>
	table, table td{ border: 1px solid #000; }

	@-ms-keyframes wiggle{0%{-ms-transform:rotate(3deg);}50%{-ms-transform:rotate(-3deg);}100%{-ms-transform:rotate(3deg);}}
	@-moz-keyframes wiggle{0%{-moz-transform:rotate(3deg);}50%{-moz-transform:rotate(-3deg);}100%{-moz-transform:rotate(3deg);}}
	@-webkit-keyframes wiggle{0%{-webkit-transform:rotate(3deg);}50%{-webkit-transform:rotate(-3deg);}100%{-webkit-transform:rotate(3deg);}}
	@keyframes wiggle{0%{transform:rotate(3deg);}50%{transform:rotate(-3deg);}100%{transform:rotate(3deg);}}
	
	

	td{vertical-align: top; padding: 10px;}
	td img{ max-width: 100%; cursor: pointer; }
	td img:hover{-ms-animation:wiggle .3s 2;-moz-animation:wiggle .3s 2;-webkit-animation:wiggle .3s 2;animation:wiggle .3s 2;}
	
	td.testStep,
	td.expectedResult,
	td.notes{
		width: 450px;
		max-width:450px;
	}
	
	td.result{ width: 100px; max-width: 100px;}
	td.stepNum{ width: 50px; max-width: 50px;}
	
	
</style>

<form name="modifyTestresult" id="modifyTestresult" method="POST" action="modifyTestresult.php" enctype="multipart/form-data">
	<div class="formRow">
		<div class="rowLabel">
			<label for="testID">Test ID:*</label>
		</div>
		<div class="rowField">
			<input type="text" name="testID" id="testID" value="<?php echo (isset($testresult) ?  $testresult->getTestID() : ''); ?>"  title="Test ID is a required field. " required="required" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="testName">Test Name:</label>
		</div>
		<div class="rowField">
			<input type="text" name="testName" id="testName" value="<?php echo (isset($testresult) ?  $testresult->getTestName() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="testNum">test Number:</label>
		</div>
		<div class="rowField">
			<input type="text" name="testNum" id="testNum" value="<?php echo (isset($testresult) ?  $testresult->getTestNum() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="pass">Pass Count:</label>
		</div>
		<div class="rowField">
			<input type="text" name="pass" id="pass" value="<?php echo (isset($testresult) ?  $testresult->getPass() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="fail">Fail Count:</label>
		</div>
		<div class="rowField">
			<input type="text" name="fail" id="fail" value="<?php echo (isset($testresult) ?  $testresult->getFail() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="taker">Test Taker:</label>
		</div>
		<div class="rowField">
			<input type="text" name="taker" id="taker" value="<?php echo (isset($testresult) ?  $testresult->getTaker() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowField">
			<?php echo (isset($testresult) ?  $testresult->getHtml() : ''); ?>
		</div>
	</div>
	<div class="formRow rowCenter">
	<!--
		<input type="hidden" name="testresultID" value="<?php echo $testresult->getID(); ?>" /> <input class="button" type="submit" value="Update" /> 
	-->	
	
	<a href="TestresultAdmin.php">Go Back</a> | <a href="http://205.189.21.88:81/deleteTestresult.php?testresultID=<?php  echo $testresult->getID(); ?>">Delete</a>
	
	</div>
</form>
<?php } ?>