<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Admin Form: "Steps" Object -->


<!-- StepsAdmin.php -->


<!--Recommended include -->
<script src="https://code.jquery.com/jquery-2.2.2.min.js"   integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="   crossorigin="anonymous"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>


<p><a href="createSteps.php">Create New Steps</a></p>
<fieldset>

	<legend>Steps</legend>

		<table id="tbl_Stepss" class="dataTable display" cellspacing="0" width="100%">

			<thead>

				<tr>

					<th>ID</th><th>Full Regression</th><th>Task and Expected Result</th><th>Pass / Fail</th>

					<th>Controls</th>

				</tr>

			</thead>

			<tbody>

				<?php

					include "include.php";

					$conn = getConnection();

							?>

			</tbody>

			<tfoot>

				<tr>

					<th>ID</th><th>Full Regression</th><th>Task and Expected Result</th><th>Pass / Fail</th>

					<th>Controls</th>

				</tr>

			</tfoot>

		</table>
</fieldset>
<a href="exportSteps.php">Download Data in CSV Format</a>
<script type="text/javascript">

		$(function(){

			/* Optional Configurations commented out */

			$("#tbl_Stepss").DataTable({

				"processing": true,

				"serverSide": true,

				"ajax": "ajaxTableSteps.php",

				//"columns" :  [ {"name": "0", "orderable": "true"}, {"name": "1", "orderable": "true"}, {"name": "2", "orderable": "true"}, {"name": "3", "orderable": "true"} ]

			});

		});
</script>
