<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Update Form: "Testcase" Object -->


<!-- modifyTestcase.php -->



<?php
	include "include.php";

	include "Testcase.php";

	$conn = getConnection(); //set to DB Conn
	$testcase = new Testcase($conn);
	$showForm = 1;
	if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {
		
		echo "Sorry editting Test was not completed... Just keep making the tests for now...";
		
		//check if there is a NEW ID for save or if one exists!!!!!!
		//taker 
		
		/*
		$testcase->getFromPost();
		$testcase->setID( $_POST["testcaseID"] );
		
		if( isset($_POST) && isset( $_POST['step'] ) ){
			$StepIDs = [];
			include "Steps.php";
			if( is_array($_POST['step']) ){
				//many options
				for($x=0; $x < sizeof( $_POST['step'] ); $x++){
					$steps = new Steps($conn);
					$steps->setID(  		$_POST['stepsID'][$x]		);
					$steps->setStep(		$_POST['step'][$x]			);
					$steps->setRegression(	$_POST['regression'][$x]	);
					$steps->setResult(		$_POST['result'][$x]		);
					$steps->setPass(		$_POST['pass'][$x]			);
					
					if( $steps->save() > 0 ){
						$StepIDs[] = $steps->getId();
					}
					
				}	
				
				//echo '<pre>'.print_r($StepIDs,true).'</pre>';
				
			}else{
				if( sizeof($_POST['step']) == 1 ){
					$steps = new Steps($conn);
					$steps->setID(  		$_POST['stepsID']	);
					$steps->setStep(		$_POST['step']		);
					$steps->setRegression(	$_POST['regression']);
					$steps->setResult(		$_POST['result']	);
					$steps->setPass(		$_POST['pass']		);
					
					if( $steps->save() > 0 ){
						$StepIDs[] = $steps->getId();
					}
				}
			}
			
			
			$testcase->setSteps( implode(',',$StepIDs) ); 
			
		} 
		
		
		
		if( $testcase->save() > 0 && $testcase->getErrorCount() == 0){
			echo "<p>Testcase updated successfully!</p>";
			echo "<p><a href='createTestcase.php'>Create new Testcase</a> or <a href='TestcaseAdmin.php'>Go back to Testcase management area</a></p>";
			$showForm = 0;
		}else{
			echo "<p>Testcase contained (".$testcase->getErrorCount().") error(s).</p>";
			echo "<p>Errors: ".$testcase->getErrors()."</p>";
			echo "<p><a href='TestcaseAdmin.php'>Go back to Testcase management area</a></p>";
		}
	*/	
	}else{
		$testcaseID = $_REQUEST["testcaseID"];

		$testcase = $testcase->load( $testcaseID );

		if( $testcase->getID() > 0 ){
		}else{
			$showForm = 0;
			echo "<p>Could not load Testcase with ID of ".$testcaseID."</p>";
		}
	}
	if( $showForm == 1){
?>
<style>
	

	@-ms-keyframes wiggle{0%{-ms-transform:rotate(3deg);}50%{-ms-transform:rotate(-3deg);}100%{-ms-transform:rotate(3deg);}}
	@-moz-keyframes wiggle{0%{-moz-transform:rotate(3deg);}50%{-moz-transform:rotate(-3deg);}100%{-moz-transform:rotate(3deg);}}
	@-webkit-keyframes wiggle{0%{-webkit-transform:rotate(3deg);}50%{-webkit-transform:rotate(-3deg);}100%{-webkit-transform:rotate(3deg);}}
	@keyframes wiggle{0%{transform:rotate(3deg);}50%{transform:rotate(-3deg);}100%{transform:rotate(3deg);}}
	
	

	td{vertical-align: top; padding: 10px;}
	td img{ max-width: 100%; cursor: pointer; }
	td img:hover{-ms-animation:wiggle .3s 2;-moz-animation:wiggle .3s 2;-webkit-animation:wiggle .3s 2;animation:wiggle .3s 2;}
	
	td.testStep,
	td.expectedResult,
	td.notes{
		width: 450px;
		max-width:450px;
	}
	
	td.result{ width: 100px; max-width: 100px;}
	td.stepNum{ width: 50px; max-width: 50px;}
	
	
</style>
<script   src="https://code.jquery.com/jquery-2.2.3.min.js"   integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="   crossorigin="anonymous"></script>

<script>
$(function(){
	$('td img').click(function(){
		window.open( $(this).attr('src') );	
	});
});	

function checkform(){
	var boxes = $('td.result select option:selected[value="Choose"]');
	console.log(boxes);
	if( boxes.length == 0 ){
		return true;
	}else{
		window.alert("Ensure all Result options are set to Passed or Failed. If the test does not apply, mark it as passed");
		return false;
	}
}

</script>


<form name="modifyTestcase" id="modifyTestcase" method="POST" action="submitTestcase.php" enctype="multipart/form-data" onsubmit="return checkform()">
	<div class="formRow">
		<div class="rowLabel">
			<label for="tid"><b>Test Case ID:*</b></label>
		</div>
		<div class="rowField">
			<?php echo (isset($testcase) ?  $testcase->getTid() : ''); ?>
			
			<!-- GET INSTANCE # -->
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="description"><b>Description:</b></label>
		</div>
		<div class="rowField">
			<?php echo (isset($testcase) ?  $testcase->getDescription() : ''); ?>
		</div>
	</div>
	<!--
	<div class="formRow">
		<div class="rowLabel">
			<label for="applicable">Test By:</label>
		</div>
		<div class="rowField">
			<input type="text" name="applicable" id="applicable" value="<?php echo (isset($testcase) ?  $testcase->getApplicable() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="requirements">Requirements:</label>
		</div>
		<div class="rowField">
			<input type="text" name="requirements" id="requirements" value="<?php echo (isset($testcase) ?  $testcase->getRequirements() : ''); ?>"  title="" disabled/>
		</div>
	</div>
	-->
	<div class="formRow">
		<div class="rowLabel">
			<label for="steps">Steps:</label>
		</div>
		<div class="rowField">
		<fieldset>
		<div id="Steps">
			<?php
			$cases = (isset($testcase) ?  $testcase->getSteps() : ''); 
			if( $cases != "" ){
				include "addStep.php";
				
				foreach(explode(",",$cases) as $c ){
					addStep_d( $c );
				}
			}
			?>
					</div>
				
				<!--<button id="addStep">Add Step</button>-->
			</fieldset>
			
		</div>
	</div>
	
	<br /><br /><br />
	
	<div class="formRow">
		<div class="rowLabel">
			<label for="name">Your Name:</label>
		</div>
		<div class="rowField">
			<input type="text" name="name" required/>
		</div>
	</div>	
	
	<div class="formRow">
		<div class="rowLabel">
			<label for="name">Browser:</label>
		</div>
		<div class="rowField">
			<input type="text" name="browser" placeholder="Chrome, Safari, IE, Firefox..." required/>
		</div>
	</div>	
	
	<div class="formRow">
		<div class="rowLabel">
			<label for="name">Device:</label>
		</div>
		<div class="rowField">
			<input type="text" name="device" placeholder="Android, iPhone, El Capitan, Win 10... " required/>
		</div>
	</div>	
	
	
	<!--
	<div class="formRow">
		<div class="rowLabel">
			<label for="comments">Comments:</label>
		</div>
		<div class="rowField">
			<?php echo (isset($testcase) ?  $testcase->getComments() : ''); ?>
		</div>
	</div>
	-->
	<div class="formRow rowCenter">	<br /> <br />
		<input type="hidden" name="testcaseID" value="<?php echo $testcase->getID(); ?>" /> 
		
		<input class="button" type="submit" value="Submit Findings" />&nbsp;&nbsp;&nbsp;&nbsp;<a href="TestcaseAdmin.php">Cancel</a>
	</div>

</form>

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
	setTimeout(function(){
		console.log("did check");
		
	},1000);
/*
	$(function(){
		$('#addStep').click(function(event){
			event.preventDefault();
			$.get("addStep.php?n=0", function( my_var ) {
				$('#Steps').append(my_var);
				
			}, 'html').always(function() {
				$('#Steps .step:last-child textarea').each(function(){
					var d = new Date();
					var n = d.getMilliseconds();
					$(this).attr('id', 'ta_' + n );
					tinymce.init({ selector: 'textarea#ta_' + n });
				});
				
				
			});
		
		});
	});
	//tinymce.init({ selector:'textarea' });
	*/
	$('textarea.notes').each(function(){
		//var d = new Date();
		var n = Date.now();
		var r = Math.floor((Math.random() * 100) + 1)
		$(this).attr('id', 'ta_' + n + r );
		tinymce.init({ selector: 'textarea#ta_' + n + r,  plugins: [
        "image paste"
    ],
    paste_data_images: true });
	});
	
	
</script>


<?php } ?>