<!--Form Generated by Brendon Irwin's Form Generator-->
<!--Admin Form: "Testcase" Object -->


<!-- TestcaseAdmin.php -->


<!--Recommended include -->
<script src="https://code.jquery.com/jquery-2.2.2.min.js"   integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="   crossorigin="anonymous"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>

<!--
<p><a href="createTestcase.php">Create New Testcase</a></p>
-->
<h1>Available Tests</h1>
<fieldset>

	<legend>Testcase</legend>

		<table id="tbl_Testcases" class="dataTable display" cellspacing="0" width="100%">

			<thead>

				<tr>

					<th>ID</th><th>Test Case ID</th><th>Description</th><th>Author</th><th>Requirements</th>

					<th>Controls</th>

				</tr>

			</thead>

			<tbody>

				<?php

					include "include.php";

					$conn = getConnection();

							?>

			</tbody>

			<tfoot>

				<tr>

					<th>ID</th><th>Test Case ID</th><th>Description</th><th>Author</th><th>Requirements</th>

					<th>Controls</th>

				</tr>

			</tfoot>

		</table>
</fieldset>
<br /><br />
<a href="exportTestcase.php">Download Data in CSV Format</a>
<script type="text/javascript">

		$(function(){

			/* Optional Configurations commented out */

			$("#tbl_Testcases").DataTable({

				"processing": true,

				"serverSide": true,

				"ajax": "ajaxTableTestcase.php",

				//"columns" :  [ {"name": "0", "orderable": "true"}, {"name": "1", "orderable": "true"}, {"name": "2", "orderable": "true"}, {"name": "3", "orderable": "true"} ]

			});

		});
</script>
